from __future__ import annotations
import hashlib
from dataclasses import dataclass
from pathlib import Path
from tree_sitter import Node, Parser
from tree_sitter_languages import get_language

OUTPUT_FILE = "utils.py"
SKIP_FILES = {OUTPUT_FILE, Path(__file__).name}


@dataclass(frozen=True)
class Item:
    kind: str
    name: str
    source: str
    file_path: str
    hash: str


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def get_python_parser() -> Parser:
    parser = Parser()
    lang = get_language("python")
    parser.language = lang
    return parser


def node_text(source_bytes: bytes, node: Node) -> str:
    return source_bytes[node.start_byte : node.end_byte].decode("utf-8", errors="replace")


def is_const_name(name: str) -> bool:
    return name.isupper()


def extract_items_from_file(path: Path, parser: Parser) -> list[Item]:
    try:
        source = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    src_bytes = source.encode("utf-8", errors="replace")
    tree = parser.parse(src_bytes)
    root = tree.root_node
    items: list[Item] = []
    for child in root.children:
        if child.type == "function_definition":
            name_node = child.child_by_field_name("name")
            if name_node is None:
                continue
            name = node_text(src_bytes, name_node)
            code = node_text(src_bytes, child)
            items.append(Item(kind="function", name=name, source=code, file_path=str(path), hash=sha256_text(code)))
        elif child.type == "class_definition":
            name_node = child.child_by_field_name("name")
            if name_node is None:
                continue
            name = node_text(src_bytes, name_node)
            code = node_text(src_bytes, child)
            items.append(Item(kind="class", name=name, source=code, file_path=str(path), hash=sha256_text(code)))
        elif child.type == "expression_statement":
            expr = child.children[0] if child.children else None
            if expr is None:
                continue
            if expr.type == "assignment":
                if len(expr.children) < 3:
                    continue
                lhs = expr.children[0]
                rhs = expr.children[-1]
                if lhs.type != "identifier":
                    continue
                name = node_text(src_bytes, lhs)
                if not is_const_name(name):
                    continue
                code = node_text(src_bytes, child)
                items.append(Item(kind="const", name=name, source=code, file_path=str(path), hash=sha256_text(code)))
            elif expr.type == "assignment_expression":
                pass
        elif child.type == "assignment":
            if len(child.children) < 3:
                continue
            lhs = child.children[0]
            if lhs.type != "identifier":
                continue
            name = node_text(src_bytes, lhs)
            if not is_const_name(name):
                continue
            code = node_text(src_bytes, child)
            items.append(Item(kind="const", name=name, source=code, file_path=str(path), hash=sha256_text(code)))
    return items


def write_utils_file(duplicates: dict[str, Item], output_path: Path) -> None:
    blocks = []
    seen_hashes = set()
    for h, item in duplicates.items():
        if h in seen_hashes:
            continue
        seen_hashes.add(h)
        blocks.append(
            f"""# Duplicate {item.kind}: {item.name}
# Source: {item.file_path}
{item.source}
"""
        )
    content = """# Auto-generated by find_duplicates_ts.py
# Contains duplicate constants / functions / classes found in the project.

""" + "\n".join(blocks)
    output_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = get_python_parser()
    all_items: dict[str, Item] = {}
    duplicates: dict[str, Item] = {}
    base_dir = Path.cwd()
    for path in base_dir.rglob("*.py"):
        if path.name in SKIP_FILES:
            continue
        items = extract_items_from_file(path, parser)
        for item in items:
            if item.hash in all_items:
                duplicates[item.hash] = all_items[item.hash]
            else:
                all_items[item.hash] = item
    output_path = base_dir / OUTPUT_FILE
    if duplicates:
        write_utils_file(duplicates, output_path)
        print(f"Found {len(duplicates)} duplicate items.")
        print(f"Wrote representative copies to: {output_path}")
    else:
        print("No duplicates found.")


if __name__ == "__main__":
    main()
